version: "3.8"

services:
  bitburner-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_MODE: production # Pass the build mode to the Dockerfile
    ports:
      - "8080:80" # Map port 8080 on the host to port 80 in the container
    restart: unless-stopped
